language: python

# use container-based infrastructure
sudo: false

deploy:
  provider: pypi
  user: baztian
  password:
    secure: bUeJtZqKYSckK9nOo3KyURl+xFrs5dq/HyzrybGBpXDRv6tX/LBIxuvo1IPS8sFhkZLmT0XksKwkJ4AMh3SDjw0+wStPLr4HMo+f4cxeL9czl8FRU96wdMq/PMUIduwXUnBYfX3KwEq4udh2PZ8ex8pLdOpJpZdoGCIly7XLpFo=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: baztian/jaydebeapi

python:
  - '2.6'
  - '2.7'

env:
  matrix:
    - TESTNAME=test_mock JDBC_DRIVER=mockdriver
    - TESTNAME=test_integration.HsqldbTest JDBC_DRIVER=org.hsqldb:hsqldb:1.8.0.10
    - TESTNAME=test_integration.SqliteXerialTest JDBC_DRIVER=org.xerial:sqlite-jdbc:3.7.2

matrix:
  include:
    - python: 2.7
      env: TESTNAME=test_integration.SqlitePyTest
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.5.3 TESTNAME=test_integration.HsqldbTest JDBC_DRIVER=org.hsqldb:hsqldb:1.8.0.10
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.7-rc1 TESTNAME=test_integration.HsqldbTest JDBC_DRIVER=org.hsqldb:hsqldb:1.8.0.10
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.5.3 TESTNAME=test_mock JDBC_DRIVER=mockdriver
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.7-rc1 TESTNAME=test_mock JDBC_DRIVER=mockdriver

before_install:
  - ci/before_install.sh

install:
  - if [ -n "$JDBC_DRIVER" ]; then mkdir classpath && export CLASSPATH=$PWD/classpath/*;fi
  - if [ "$JDBC_DRIVER" == "mockdriver" ]; then (cd mockdriver && mvn package && mv target/mockdriver.jar $CLASSPATH/); elif [ -n "$JDBC_DRIVER" ]; then mv $(ci/mvnget.sh $JDBC_DRIVER) $CLASSPATH/;fi
  - source $HOME/myvirtualenv/bin/activate
  - pip install -e .
  - pip install -r test-requirements.txt
  - if [ -z "$JYTHON" ]; then pip install coveralls ;fi

script:
  - if [ -z "$JYTHON" ]; then PY="coverage run --source jaydebeapi"; else PY="python" ;fi
  - $PY test/testsuite.py $TESTNAME

after_success:
  - if [ -z "$JYTHON" ]; then coveralls ;fi
